### ISSUE TITLE
Veranstaltungsort - Adresse

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-website#1]
Wir haben ein Feld "Veranstaltungsort - Adresse" (Textarea) angelegt.

Das müßte bei Veranstaltungsbeiträgen gestylt werden. Bisher erscheint es nur als Fließtext.

Textarea haben wir gewählt, weil wir ja nicht wissen, ob wir nicht mal mehr Zeilen als 2 für eine Adresse brauchen werden.

**Comment by SniperSister** [comment]
Done, bitte checken und closen wenn es passt

**Comment by Skeeve** [comment]
Perfekt! Danke!
