### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-website#11]
Wir benötigen ein Monitoring mit Alarming das idealerweise auch dann noch läuft, wenn die Cloud Platform abgeschaltet wurde.

Ich hab's initial an Dich @SniperSister assigned, weil Du gestern meintest, es könnte in Dein besthendes icinga integriert werden.

**Comment by SniperSister** [comment]
Hab die Seite in mein Icinga aufgenommen
