### ISSUE TITLE
XML-Sitemaps für Suchmaschinen erstellen und Indexierung überwachen

### ISSUE THREAD

**Issue by skempe-4fb** [SIWECOS/siwecos-website#15]
Allgemein: Eine XML-Sitemap kann beim Crawling und der folgenden Indexierung helfen. In Bezug auf die Rankings haben diese in der Regel überhaupt keine positive oder negative Auswirkung. Bei der Diagnose eventueller Probleme sind sie aber unverzichtbar.

Problem: Sitemap-Index kann gelesen werden, enthält aber Fehler
HTTP-Fehler: 404
https://siwecos.de/sitemap_index.xml

Best Practices: 
-- legen Sie die kanonische Version jeder Seite fest
-- für unterschiedliche Seitentypen (CMS-Seiten, WIKI …) jeweils eine eigene XML-Sitemap erstellen
-- für unterschiedliche Segmente (Sprachen/Länder/…) jeweils eine eigene XML-Sitemap erstellen
--  auf zusätzliche Medientypen wie Video und Bilder verweisen 
-- nicht mehr als 50 000 URLs  (50MB) für eine einzelne Sitemap
-- einen Link zu sitemap.xml in robots.txt aufnehmen

Momentan unterstützt Google das Attribut priority nicht in Sitemaps.

**Comment by SniperSister** [comment]
@skempe-4fb hab die DE und EN Sitemap für's CMS in der robots.txt ergänzt

@Skeeve kannst du mal nach einer XML Sitemap für's mediawiki gucken?

**Comment by Skeeve** [comment]
Bitte mal testen.

Habe eine sitemap (versucht) anzulegen mit

```
php maintenance/generateSitemap.php --memory-limit=50M --fspath=$PWD/sitemap/ --identifier=wikisiwecosde --urlpath=/wiki/sitemap/ --server=https://siwecos.de --compress=yes
```

Nach Anleitung von https://www.mediawiki.org/wiki/Manual:GenerateSitemap.php

Wenn das korrekt ist, können wir einen cronjob anlegen.

**Comment by SniperSister** [comment]
Unter welcher URL müsste die dann jetzt erreichbar sein?

**Comment by Skeeve** [comment]
Ich hätte `https://siwecos.de/wiki/sitemap/` erwartet, da gibt's aber ein **Forbidden**.

**Comment by SniperSister** [comment]
Ok, klemmst du dich mal dahinter und gibst bescheid sobald es rennt?

**Comment by Skeeve** [comment]
Pfad war verkehrt

```
https://siwecos.de/wiki/sitemap/sitemap-index-wikisiwecosde.xml
```

**Comment by SniperSister** [comment]
ist ebenfalls in der robots.txt @skempe-4fb bitte checken

**Comment by skempe-4fb** [comment]
Hallo zusammen, vielen Dank für die schnelle Umsetzung. Ich war heute leider nicht in der Agentur, daher entschuldigt bitte die späte Rückmeldung. Die Interessanten Tickets kommen ja erst xD noch ...

Die Joomla XML-Sitemaps für DE und EN  sind aus meiner Sicht technisch in Ordung. 

https://siwecos.de/component/osmap/?view=xml&id=1
https://siwecos.de/en/component/osmap/?view=xml&id=1

Ich kann Sie leider mit den 4fB-Rechten in der Search Console von Google nicht einreichen, um sie zu testen. Der Crawler wird sie aber die Tage über den Eintrag in der robots.txt finden. Über den Eintrag in der robots sind wir auch flexibel, was die XML-Sitemap Pfade angeht. Ich habe die Joomla Sitemaps auch per Ping übermittelt.

Es gibt verschiedene Möglichkeiten, Ihre Sitemap für Google zugänglich zu machen:

Reichen Sie sie über das Sitemaps-Tool der Search Console bei Google ein.

Fügen Sie an einer beliebigen Stelle Ihrer robots.txt-Datei die folgende Zeile ein, um den Pfad zu Ihrer Sitemap anzugeben: Sitemap: http://example.com/sitemap_location.xml.

Verwenden Sie die "Ping"-Funktion, damit wir Ihre Sitemap noch einmal crawlen. Senden Sie eine HTTP GET-Anfrage wie diese: https://www.google.com/ping?sitemap=<complete_url_of_sitemap>.
Beispiel:  https://www.google.com/ping?sitemap=https://example.com/sitemap.xml

Die Sitemaps vom Media Wiki geben relative URLs aus, Sorry - Ich wollte euch Beispiel Sitemaps anhängen, die Richtlinie gibt leider vor nur absolute Pfade mit kanonisch erreichbaren URLS (HTTP-Statuscode 200) auszugeben.

Support Link von Google: https://support.google.com/webmasters/answer/183668?hl=de

"Verwenden Sie konsistente, vollständig qualifizierte URLs. Google crawlt Ihre URLs genau so, wie Sie sie angegeben haben. Wenn sich Ihre Website beispielsweise unter http://www.example.com/ befindet, verwenden Sie als URL nicht /http://example.com/ (ohne www) oder ./meineseite.html (eine relative URL)."

Die bitte nochmal gerade ziehen. Morgen erstelle ich dann die nächsten Tickets zu Markup und strukturierte Daten.

Danke!

**Comment by Skeeve** [comment]
@skempe-4fb Da ich keine Ahnung von Sitemaps habe, wäre es hilfreich, Du könntest mir an den wiki Sitemaps zeigen, wo was nicht ist, wie erwartet. Ich habe die Sitemaps (s.o.) per wikimedia-Script erstellen lassen. Was die Auswirkungen der einzelen Optionen hat und was genau die Ausgabedateien bedeuten erschließt sich mir noch nicht.

**Comment by skempe-4fb** [comment]
@Skeeve Die Ausgabe der "loc" im Sitemap-Index sind relative URLS (/wiki/sitemap/sitemap-wikisiwecosde-NS_0-0.xml.gz), die URLS bitte absolut (https://siwecos.de/wiki/sitemap/sitemap-wikisiwecosde-NS_0-0.xml.g) ausgeben. 

Zum Beispiel:

<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap>
<loc>/https://siwecos.de/wiki/sitemap/sitemap-wikisiwecosde-NS_0-0.xml.gz</loc>
<lastmod>2019-06-12T06:48:36Z</lastmod>
</sitemap>

Dann sollte alles soweit passen und ich kann sie testen, Ich werde doch erst morgen wieder im Büro sein. Schaue aber später nochmal rein.

**Comment by Skeeve** [comment]
@SniperSister Neues Kommando für den cronjob:

```
php maintenance/generateSitemap.php --memory-limit=50M --identifier=wikisiwecosde --fspath=$PWD/sitemap/ --urlpath=https://siwecos.de/wiki/sitemap/ --server=https://siwecos.de --compress=yes
```

Lesbar:
```
php maintenance/generateSitemap.php \
  --memory-limit=50M \
  --identifier=wikisiwecosde \
  --fspath=$PWD/sitemap/ \
  --urlpath=https://siwecos.de/wiki/sitemap/ \
  --server=https://siwecos.de \
  --compress=yes
```

**Comment by SniperSister** [comment]
Done!

**Comment by skempe-4fb** [comment]
[sitemaps_nonindexable_urls_in_sitemap.xlsx](https://github.com/SIWECOS/siwecos-website/files/3287607/sitemaps_nonindexable_urls_in_sitemap.xlsx)

Sieht jetzt gut aus mit den absoluten Pfaden. Beim testen gerade sind noch einige URLS in der Sitemap mit HTTP-Statuscode 400 enthalten. Diese bitte ausschließen.

**Comment by Skeeve** [comment]
Die sitemap wird nur per cronjob aktualisiert und am Wiki wurde heute gearbeitet. Morgen sollte die Liste okay sein.

**Comment by skempe-4fb** [comment]
Ok danke. Wir arbeiten die 404er nach Bedarf bei den internen und externen Links noch ab. Ich erstelle dann am besten einen Test Crawl am Montag, dann sehen wir den aktuellen Status nach dem der Job durchgelaufen ist. Nicht wundern wenn morgen ggf. ein paar neue Tickets erstellt werden, ich konnte die Woche leider nur einen Tag im Office arbeiten. Schönes Wochenende und bis nächste Woche.

**Comment by skempe-4fb** [comment]
Aktuell noch eine Seite die in der Sitemap mit http-Status 404 ausgeben wird: https://siwecos.de/wiki/Kategorie:Generell

Wir sollten generell nochmal über das löschen von Seiten sprechen. Idealerweise werden Seiten die von außen verlinkt sind und Zugriffe haben, per 301 auf eine Inhaltlich passende und somit relevante Seite weitergeleitet. Diese Seite hat keinen Value und kann somit in dem Zustand bleiben.

**Comment by Skeeve** [comment]
Und auch heute wird am Wiki gearbeitet.

**Comment by skempe-4fb** [comment]
Seitens der Suchmaschinen sind die Sitemaps ohne weitere Fehler verarbeitet und ich kann dieses Ticket schließen.
![sitemap index status check google](https://user-images.githubusercontent.com/51449199/59678962-f2d6d700-91cd-11e9-8118-4594969a8942.JPG)
