### ISSUE TITLE
Aussagekräftigen Meta-Titel und -Description für die Homepage (CMS) einpflegen

### ISSUE THREAD

**Issue by skempe-4fb** [SIWECOS/siwecos-website#16]
Ich hoffe das passt so, es geht darum die Fokus Keywords in die für Suchmaschinen relevanten Stellen zu bekommen und die ClickThroughRate aus den Suchergebnisseiten zu verbessern. Was haltet Ihr von dem Vorschlag:

Titel: 
Webseiten Sicherheitscheck für KMU - SIWECOS

Description: 
Sichere Webseiten und Content Management. Systeme “den kostenlosen Sicherheitscheck für KMU  &#10148; gleich Starten"

![Titel und Meta Description neu - Homepage](https://user-images.githubusercontent.com/51449199/59614245-a3869d00-9120-11e9-9d64-5b1d0e312b1d.png)

**Comment by SniperSister** [comment]
Fine for me! Global setzen? Oder wollt ihr abweichende Tags auf den Unterseiten?

**Comment by skempe-4fb** [comment]
Idealerweise abweichende Tags für die jeweilige Seite, die wir optimieren wollen - Suchmaschinen meiden Duplikate und bewerten den Qualitätsfaktor niedrig.

**Comment by SniperSister** [comment]
Ok, kann ich da von euch auch da vorschläge bekommen?

**Comment by skempe-4fb** [comment]
Ja, ich erstelle euch die Templates anhand der Fokus Keywords. Wir stimmen alles vorher ab. Nutzt Ihr im Joomla bereist ein Plugin für SEO? Frage wegen strukturierten Daten für das Logo, Unternehmen usw. Da werde ich ein separates Ticket für aufmachen.

**Comment by SniperSister** [comment]
Nein, wir nutzen da kein Plugin, ist für strukturierte Daten aber auch nicht notwendig

**Comment by skempe-4fb** [comment]
Ja sicher, denke auch das ist ohne technisch sauberer zu lösen. Wollte mich nur erkundigen. Was haltet Ihr von Breadcrumbs, die können wir auch nach schema.org im JSON-Format (idealerweise) auszeichnen um die UX besser zu machen und für SEO die internen Links etwas zu pushen. Aktuell sind Auszeichnungen denkbar für:

--- Logo
--- WebPage
--- Organization
--- BreadcrumbList (optional)
--- Kundenbewertungen (aggregateRating) falls vorhanden und oder pflegbar
--- Bilder und Videos 
--- Article
--- SoftwareApplication
--- Events

**Comment by skempe-4fb** [comment]
Vier davon sind Pflicht und Kür :)

**Comment by skempe-4fb** [comment]
Hallo,

ich habe euch jetzt Beispiele für die organischen Landingpages erstellt. Wir können die gerne nächste Woche durchgehen oder Ihr bindet die Meta-Daten ein. VG Stefan

**Comment by skempe-4fb** [comment]
[titel und meta informationen für siwecos.txt](https://github.com/SIWECOS/siwecos-website/files/3436485/titel.und.meta.informationen.fur.siwecos.txt)

**Comment by SniperSister** [comment]
Danke, ist eingepflegt!
