### ISSUE TITLE
Bing Webmaster Tools einrichten

### ISSUE THREAD

**Issue by skempe-4fb** [SIWECOS/siwecos-website#17]
Bitte einen AC bei Bing erstellen und unsere google.ads@4fb.de Adresse als Nutzer hinzufügen. 

https://www.bing.com/toolbox/webmaster/

Könnt Ihr mir ggf. die Rechte in der Google Search Console als Nutzer erhöhen? Dann kann ich die XML-Sitemaps hinzufügen und testen.

**Comment by SniperSister** [comment]
Done - bitte prüfen und Ticket schließen wenn's passt

**Comment by skempe-4fb** [comment]
Prima, danke, passt soweit.
