### ISSUE TITLE
 Strukturierte Daten erstellen, testen und veröffentlichen

### ISSUE THREAD

**Issue by skempe-4fb** [SIWECOS/siwecos-website#18]

**Comment by skempe-4fb** [comment]
Format: Strukturierte Daten müssen in einem der drei etablierten Formate Microdata, RDFa oder JSON-LD vorliegen. Google empfiehlt Letzteres.

Zugänglichkeit: Seiten mit strukturierten Daten müssen für den Googlebot zugänglich sein. Access-Control-Methoden (z. B. via robots.txt oder noindex) verhindern das Auslesen der Metadaten.

Content-Äquivalenz: Das JSON-LD-Markup darf lediglich Entitäten beschreiben, die auch im HTML-Code beschrieben werden.

Relevanz: Ein JSON-LD-Markup sollte sich lediglich auf relevante Entsprechungen der verwendeten Datentypen beziehen. Ein Webseitenbetreiber, der eine technische Anleitung als Rezept auszeichnet, verstieße beispielsweise gegen die Richtlinie der Relevanz.

Vollständigkeit: Alle im JSON-LD-Markup aufgeführten Datentypen (types) müssen vollständig und inklusive der erforderlichen Eigenschaften (properties) ausgezeichnet werden. Datentypen, bei denen essenzielle Eigenschaften fehlen, eignen sich nicht für erweiterte Suchergebnisse.

Spezifität: Linked-Data-Projekte wie Schema.org bieten eine Vielzahl von Datentypen. Um die eigenen Inhalte für eine erweiterte Suchergebnisdarstellung zu qualifizieren, sollten Webseitenbetreiber Schemata so spezifisch wie möglich wählen.

Aktuell sind Auszeichnungen denkbar für:

--- Logo
--- WebPage
--- Organization
--- BreadcrumbList (optional)
--- Kundenbewertungen (aggregateRating) falls vorhanden und oder pflegbar
--- Bilder und Videos
--- Article
--- Sitelinks Searchbox
--- SoftwareApplication
--- Events

Was benötigt Ihr von mir -- am effektivsten für eure Website/ Thema sind Nummer 1-6. Habe eine Beispiele Dateien erstellt.

**Comment by skempe-4fb** [comment]
[Beispiel Json Organization.txt](https://github.com/SIWECOS/siwecos-website/files/3298003/Beispiel.Json.Organization.txt)
[Beispiel Json Breadcrumbs.txt](https://github.com/SIWECOS/siwecos-website/files/3298004/Beispiel.Json.Breadcrumbs.txt)

**Comment by skempe-4fb** [comment]
Bestehende Seiten korrigieren:
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fsiwecos.de%2Fcms%2Fcms-matrix%2F

**Comment by skempe-4fb** [comment]
Testtool strukturierte Daten:
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fsiwecos.de%2Fcms%2Fcms-matrix%2F

**Comment by SniperSister** [comment]
Habe integriert was sich mit vernünftigem Aufwand abbilden lies: https://siwecos.de/cms/contao

**Comment by skempe-4fb** [comment]
Prima!

Organization, BreadcrumbList und Article werden laut Test-Tool fehlerfrei in den Seiten ausgegeben. Beobachten das weiter im Search Console Report.
