### ISSUE TITLE
Fehler in FF 60.0.1 (Mac)

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-website#2]
Eventuell wird ja gerade gebastelt.

Ansonsten: Siehe Bild.
<img width="1515" alt="bildschirmfoto 2018-09-26 um 20 00 46" src="https://user-images.githubusercontent.com/725404/46099441-1339ae00-c1c7-11e8-94b0-7e5c7e9f6011.png">

**Comment by SniperSister** [comment]
WTF?! Rechnerübergreifend nachvollziehbar?

**Comment by Skeeve** [comment]
Gleicher Rechner - Anderer Browser - Läuft.

**Comment by Skeeve** [comment]
Nachtrag - Sorry!

NoScript Plugin sollte man auch mitteilen, dass man der Seite vertraut.

Dann bleibt von den Meldungen nur noch:

<img width="1256" alt="bildschirmfoto 2018-09-26 um 23 03 56" src="https://user-images.githubusercontent.com/725404/46109358-9d424080-c1e0-11e8-920b-d35fea8bf9e7.png">

**Comment by Skeeve** [comment]
Mit No-Script disabled bleibt

```
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
```

**Comment by SniperSister** [comment]
Letzteres ist korrekt.

**Comment by SniperSister** [comment]
Können wir das schließen?
