### ISSUE TITLE
Marketing-Kampagnen und externe Kommunikation effizient tracken

### ISSUE THREAD

**Issue by skempe-4fb** [SIWECOS/siwecos-website#20]
Hallo, 

könnt Ihr bitte unsere IP-Adresse 83.236.182.28 über das Matomo Backend ausschließen. Am besten eure IPs auch, damit die internen Zugriffe die Statistiken nicht  verwässern. 

Ich empfehle auch Ziele einzurichten (Scan ohne Registrierung, Registrierung, Anmeldung, Aktivierung eines Konto´s, Scans im eingeloggten Zustand und Downloads. Bin nicht sicher ob noch weitere Ereignisse eine Rolle spielen. 

Habe gerade gesehen, das es eine Ziel-Seite gibt: https://siwecos.de/willkommen-bei-siwecos/ -- hier können doppelte Aufrufe entstehen, wäre aber der Einfachheit halber ohne Aufwand über das Backend, als Ziel einzurichten.

Wir können gerne noch prüfen, ob wir den Links aus der Aktivierungsemail gesonderte Kampagnenparameter anhängen, dann haben wir eine Kontrollmenge über die aktivierten Accounts. 

Kampagnen Name (pk_campaign)
Kampagnen Medium (pk_medium)
Kampagnen Quelle (pk_source)
Kampagnen Keyword (pk_keyword)
Kampagnen Content (pk_content)
Kampagnen ID (pk_cid)

Die müssten dann Serverseitig übergeben werden. Wenn Ihr da Unterstützung benötigt haben wir einen guten AP im Haus, der Support geben kann.

**Comment by MacMic** [comment]
83.236.182.28 aus dem Tracking genommen

**Comment by skempe-4fb** [comment]
Bekommt Ihr evtl. eure IP oder IP´s auch ausgeschlossen. Wenn nicht, sind Ungenauigkeiten je nach Hypothese mit den Daten kein Weltuntergang :)
