### ISSUE TITLE
Strukturierte Daten: SiteNavigationElement

### ISSUE THREAD

**Issue by skempe-4fb** [SIWECOS/siwecos-website#21]
Rich Results: Rich Snippets & Rich Cards
Die Verwendung von strukturierten Daten ist nicht zwingend notwendig, damit Google Suchergebnisse visuell aufbereitet. Sie ist aber der wichtigste Schritt, um eure Internetseite prominenter darstellen zu lassen.

https://schema.org/SiteNavigationElement

**Comment by SniperSister** [comment]
Ist ergänzt, bitte testen, danke!

**Comment by skempe-4fb** [comment]
Test ist fehlerfrei, nächste Woche arbeiten wir Onpage. Schönes Wochenende!
