### ISSUE TITLE
Strukturierte Daten: Sitelinks-Suchfeld

### ISSUE THREAD

**Issue by skempe-4fb** [SIWECOS/siwecos-website#22]
Bei bestimmten Suchanfragen wird in den Sitelinks direkt eine Suchbox angezeigt. Wenn ihr diese nicht auszeichnet, wird eine neue Google Suche nur für diese Domain ausgelöst. Durch die richtige Einbindung von schema.org könnt ihr hier stattdessen eure interne Suchfunktion verknüpfen und die Suche wird direkt auf die Suchergebnisseite eurer Internetseite geleitet.

https://developers.google.com/search/docs/data-types/sitelinks-searchbox

**Comment by SniperSister** [comment]
Deploy ist angeschoben, schau bitte morgen mal drauf ob's so passt

**Comment by skempe-4fb** [comment]
Ja prima - dann schaue ich mir das morgen an. Top - eure Qualität und Geschwindigkeit!

**Comment by skempe-4fb** [comment]
Ist leider nicht Live!?

**Comment by skempe-4fb** [comment]
![Screen Shot on 2019-07-05 at 17_00_06](https://user-images.githubusercontent.com/51449199/60730873-673ba500-9f46-11e9-8139-d86476917e9c.png)

**Comment by SniperSister** [comment]
Doch, Type "WebSite"

**Comment by skempe-4fb** [comment]
Sorry - dachte es ist das Ticket für die Site-Links. Alles klar, dann mache ich das zu. Danke und schönes Wochenende!
