### ISSUE TITLE
Tag-Seiten auf passende Zielseiten weiterleiten

### ISSUE THREAD

**Issue by skempe-4fb** [SIWECOS/siwecos-website#24]
Bitte die Tag-Seiten auf passende URLs weiterleiten. Aktuell leiten global alle auf die Startseite.

[siwecos.de Index Coverage Drilldown 2019-07-25.xlsx](https://github.com/SIWECOS/siwecos-website/files/3432087/siwecos.de.Index.Coverage.Drilldown.2019-07-25.xlsx)

**Comment by SniperSister** [comment]
@skempe-4fb kann es sein dass die falsche Datei angehangen ist? sieht so aus als gehört die zu #23

**Comment by skempe-4fb** [comment]
[siwecos.de Performance 2019-07-29.xlsx](https://github.com/SIWECOS/siwecos-website/files/3443069/siwecos.de.Performance.2019-07-29.xlsx)

@SniperSister  Jetzt sollte es passen. Sorry vermutlich war die Bezeichnung der Donwload Datei identisch und ich habe Sie überschrieben gehabt. Sind beide frisch hochgeladen :)

**Comment by SniperSister** [comment]
Es gibt leider für relativ viele Tags kein passenderes Redirect-Ziel, das was ich sinnvoll weiterleiten konnte habe ich aber erledigt
