### ISSUE TITLE
Meta Description Homepage anpassen

### ISSUE THREAD

**Issue by skempe-4fb** [SIWECOS/siwecos-website#25]
@SniperSister Hallo David, evtl hat sich da beim kopieren oder im Editor ein kleiner Fehler eingeschlichen. Hier nochmal die Beschreibung:"SIWECOS steht für „Sichere Webseiten und Content Management Systeme“&#10144; jetzt kostenlosen Sicherheitscheck starten."

Sollte es mit der Einbindung von Symbolen Probleme geben, dann finden wir dafür eine andere Lösung.

![Screen Shot on 2019-07-29 at 17_51_58](https://user-images.githubusercontent.com/51449199/62063043-7272af80-b22a-11e9-9444-90e50a963c19.png)

**Comment by SniperSister** [comment]
Fixed!
