### ISSUE TITLE
Registrierungsseite

### ISSUE THREAD

**Issue by skempe-4fb** [SIWECOS/siwecos-website#28]
https://siwecos.de/willkommen-bei-siwecos/ den Robots-Tag auf noindex, follow setzen. Danke.

**Comment by SniperSister** [comment]
duplikat von #26 ?

**Comment by skempe-4fb** [comment]
Ist ein Duplikat. Als ich die 26 erstellt habe wurde Sie mir in der Liste nicht angezeigt.
