### ISSUE TITLE
WIKI - Zurück zur Siwecos-Webseite auf rel="follow" setzen

### ISSUE THREAD

**Issue by skempe-4fb** [SIWECOS/siwecos-website#30]
<a target="_self" rel="nofollow" class="external text" href="https://siwecos.de/" style="border: 1px dotted firebrick;">Zurück zur Siwecos-Webseite</a>

Den Text Link vom WIKI auf die Startseite von Siwecos bitte auf rel="follow" setzen; Wichtig das hier keine PR Beschneidung stattfindet. Idealerweise platzieren wir hier einen Text der auch als Call-To-Action dient und die Nutzer auf den Webseiten-Check oder den Schnell-Check abholen.

Zurück zur Siwecos-Website bitte ändern in >> hier kostenlos den Siwecos Schnell-Check ausführen << oder >> Website-Checks in wenigen Sekunden << geändert werden. 

Auch ein Badge oder Teaser kann hier helfen. Bilder sagen manchmal mehr als Worte. Eure Entscheidung.

**Comment by PetraStruck** [comment]
So in etwa? Siehe https://siwecos.de/wiki2/Hauptseite

**Comment by SniperSister** [comment]
Der Link war noch als nofollow ausgezeichnet, hab das durch eine Ausnahme für die Domain jetzt angepasst: https://www.mediawiki.org/wiki/Manual:$wgNoFollowDomainExceptions

**Comment by Skeeve** [comment]
Du hast meinen schönen Code weggeworfen…

Deins ist natürlich eleganter.

Frage: Da jetzt kein rel mehr drin steht, steht da also auch kein rel="follow".

Hat das Konsequenzen?

**Comment by SniperSister** [comment]
> Frage: Da jetzt kein rel mehr drin steht, steht da also auch kein rel="follow".

`follow` ist der Default-Wert und daher ist das Attribut in dem Fall redundant

**Comment by Skeeve** [comment]
Dann schaeun wir mal, ob @skempe-4fb hier abschließt…

**Comment by skempe-4fb** [comment]
Alles klar, Lösung passt und ist abgenommen - Danke!
