### ISSUE TITLE
WIKI - Verlinkung (sitewide) zum SIWECOS Webseiten-Check

### ISSUE THREAD

**Issue by skempe-4fb** [SIWECOS/siwecos-website#31]
Der interne Link Rank misst den Fluss von "Link Juice" zwischen den Seiten Ihrer Website.

Der Interne Link Score für die Homepage (Joomla) kann durch einen Link im WIKI-Template (links unter Siwecos - alternativ - aber nicht so effektiv im Footer) optimiert werden: 
Keyword Anker „SIWECOS Sicherheitscheck oder Schnell-Check“ Siehe Screenshot.
![wiki-template-link-mit-fokus-keyword-zur-startseite](https://user-images.githubusercontent.com/51449199/64187980-d283f380-ce71-11e9-96fa-ad2bd0185354.JPG)

**Comment by Skeeve** [comment]
Schließen?
