### ISSUE TITLE
ALT-Attribute als Inhalt für Suchmaschinen

### ISSUE THREAD

**Issue by skempe-4fb** [SIWECOS/siwecos-website#34]
Hallo, bitte das ALT-Attribut als beschreibenden Text nutzen. 

Bitte nicht den Dateinamen verwenden.

https://siwecos.de/wiki/images/4/45/Seal_siwecos_static_final.png

Beispiel: alt="Das Siwecos Siegel steht für Sichere Webseiten und Content Management Systeme"

ALT-Attribute als Inhalt für Suchmaschinen:
Suchmaschine-Robots sind zwar sehr ausgereifte Datenerfasser, sie verfügen aber noch nicht über eine effiziente Bilderkennung und können nur Text lesen. Aus diesem Grund indizieren Suchmaschinen Bilddaten anhand zusätzlicher Informationen, die Crawler auf einer Website finden. Ein wichtiger Bestandteil zur Erkennung von Bildinhalten ist dabei das Alt-Attribut.

**Comment by PetraStruck** [comment]
Done!
