### ISSUE TITLE
Siwecos Siegel auf Unterseiten im WIKI platzieren

### ISSUE THREAD

**Issue by skempe-4fb** [SIWECOS/siwecos-website#35]
Hallo,

bitte den ALt-Tag vom Siegel anpassen und dann auf wichtigen Unterseiten im WIKI platzieren. 
Auf der Seite: https://siwecos.de/wiki2/Hauptseite ist das Siegel überflüssig, da wir hier den Text 
Link mit dem Call to Action als do-follow link platziert haben. 

Es wird immer nur der erste Link und Anker zu einer Zielseite bewertet. Eine Kombination Text und Bildlink geht auch. 

Daher bitte das Siegel auf den wichtigen Seiten (siehe Liste) einbauen und auf der Hauptseite rausnehmen.

[siwecos.de Performance 2019-09-12.xlsx](https://github.com/SIWECOS/siwecos-website/files/3604827/siwecos.de.Performance.2019-09-12.xlsx)

Danke!

**Comment by PetraStruck** [comment]
Ich verschiebe das mal auf Montag. Deine Liste müssen wir uns dann gemeinsam anschauen. Ich würde denken, dass es einfacher sein dürfte, einen vernünftigen Link zu Siwecos.de im Footer (also generell einzubauen). Wobei ich da auch erstmal schauen muss, wie man den Footer editieren kann.

**Comment by PetraStruck** [comment]
Habe in meinem Test-Wiki mal ein Siegel-Logo rechts unten im Footer eingebunden: https://wiki.petra-struck.de/Hauptseite - Wäre das eine Alternative? Das Logo kann ich auch verkleinern oder grafisch kann es natürlich anders gestaltet werden. Ist erstmal nur ein Test.

Auf diese Weise würde es ohne größeren Aufwand automatisch auf allen Wiki-Seiten erscheinen.
