### ISSUE TITLE
WIKI Hauptseite: Titel und Meta-Description Vorschlag

### ISSUE THREAD

**Issue by skempe-4fb** [SIWECOS/siwecos-website#36]
Seitentitel: Siwecos WIKI rund um Webseitensicherheit

Meta-Description: Im Fokus stehen Erklärungen und andererseits wird auch stark auf die Sensibilisierung von KMU im Bereich Cyber-Sicherheit gesetzt.

**Comment by PetraStruck** [comment]
Ich muss schauen, wo und ob das im Wiki machbar ist. Kann ich mich erst Montag drum kümmern.

**Comment by PetraStruck** [comment]
Da könnte diese Extension helfen, ich spreche das mit Stephan ab.
https://www.mediawiki.org/wiki/Extension:Add_HTML_Meta_and_Title#Installation
