### ISSUE TITLE
Navbar scrollt weg

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-website#4]
Vergleiche bitte mit momentaner SIWECOS Seite. Die navbar bleibt am oberen Rand. In der neuen Version scrollt sie aus dem Sichtberecch.

**Comment by SniperSister** [comment]
Deploy zur Staging läuft, bitte prüfen

**Comment by Skeeve** [comment]
passt. Danke

**Comment by SniperSister** [comment]
Deploy nach live läuft
