### ISSUE TITLE
Siegel - Timeout verringern

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-website#8]
Die Daten fürs Siegel werden per JHttpFactory::getHttp geholt.

Wenns Backend down ist, läuft dies in einen Timeout. Den sollten wir, wenn möglich, verringern.

**Comment by SniperSister** [comment]
Memo für morgen: Siegel Push statt Siegel pull. Mehr dazu morgen..

**Comment by SniperSister** [comment]
Fixed durch die Umstellungs auf's CDN
